version: '3.8'

services:
  backend:
    image: japanese-hotel-server
    container_name: springboot-server-container
    build:
      context: ./japanese-hotel-server
      dockerfile: Dockerfile
    ports:
      - "9191:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/japanese_hotel_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpass
    networks:
      - app-networks
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: japanese_hotel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-networks

volumes:
  db-data:

networks:
  app-networks:
    driver: bridge

