version: '3.8'

services:
  frontend:
    build:
      context: ./japanese-hotel-client
      dockerfile: Dockerfile
    ports:
      - "5173":"5173"
    networks:
      - app-networks

  backend:
    build:
      context: ./japanese-hotel-server
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/japanese_hotel_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    networks:
      - app-networks
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: japanese_hotel_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-networks

volumes:
  db-data:

networks:
  app-networks:
    driver: bridge
